import React, { useEffect, useRef } from 'react';
import { Network, Eye, Brain, HelpCircle } from 'lucide-react';

interface KnowledgeGraphProps {
  graphData?: {
    nodes: Array<{
      id: string;
      label: string;
      size: number;
      color: string;
      cluster: number;
    }>;
    edges: Array<{
      source: string;
      target: string;
      weight: number;
    }>;
  };
  insights?: {
    gaps: string[];
    questions: string[];
    clusters: Array<{
      id: number;
      label: string;
      concepts: string[];
    }>;
  };
  onQuestionClick: (question: string) => void;
  isVisible: boolean;
  onToggle: () => void;
}

export const KnowledgeGraph: React.FC<KnowledgeGraphProps> = ({
  graphData,
  insights,
  onQuestionClick,
  isVisible,
  onToggle,
}) => {
  const graphRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (isVisible && graphData && graphRef.current) {
      // Here you would integrate with a graph visualization library like D3.js, vis.js, or sigma.js
      // For now, we'll show a placeholder
      renderGraph();
    }
  }, [isVisible, graphData]);

  const renderGraph = () => {
    if (!graphRef.current || !graphData) return;

    // Placeholder for actual graph rendering
    // You would use a library like D3.js or vis.js here
    const nodeCount = graphData.nodes?.length || 0;
    const edgeCount = graphData.edges?.length || 0;
    
    graphRef.current.innerHTML = `
      <div class="flex items-center justify-center h-full text-gray-400">
        <div class="text-center">
          <div class="w-12 h-12 mx-auto mb-4 flex items-center justify-center">
            <svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
            </svg>
          </div>
          <p>Knowledge Graph Visualization</p>
          <p class="text-sm mt-2">${nodeCount} concepts, ${edgeCount} connections</p>
          ${nodeCount > 0 ? '<p class="text-xs mt-1 text-green-400">✓ Generated by Google Knowledge Graph</p>' : '<p class="text-xs mt-1 text-yellow-400">Using fallback analysis</p>'}
        </div>
      </div>
    `;
  };

  if (!isVisible) {
    return (
      <button
        onClick={onToggle}
        className="fixed bottom-6 right-6 p-3 bg-purple-600 text-white rounded-full shadow-lg hover:bg-purple-700 transition-colors z-50"
        title="Show Knowledge Graph"
      >
        <Brain className="w-6 h-6" />
      </button>
    );
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4">
      <div className="bg-gray-800 rounded-xl border border-gray-700 w-full max-w-6xl h-5/6 flex flex-col">
        {/* Header */}
        <div className="p-6 border-b border-gray-700 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <Brain className="w-6 h-6 text-purple-500" />
            <h2 className="text-xl font-semibold text-white">Knowledge Graph Analysis</h2>
          </div>
          <button
            onClick={onToggle}
            className="p-2 text-gray-400 hover:text-white transition-colors"
          >
            <Eye className="w-5 h-5" />
          </button>
        </div>

        <div className="flex-1 flex">
          {/* Graph Visualization */}
          <div className="flex-1 p-6">
            <div
              ref={graphRef}
              className="w-full h-full bg-gray-900 rounded-lg border border-gray-600"
            />
          </div>

          {/* Insights Panel */}
          <div className="w-80 border-l border-gray-700 p-6 overflow-y-auto">
            <div className="space-y-6">
              {/* Summary */}
              {insights?.summary && (
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4">Analysis Summary</h3>
                  <div className="p-3 bg-gray-700 rounded-lg">
                    <p className="text-gray-300 text-sm">{insights.summary}</p>
                  </div>
                </div>
              )}

              {/* Suggested Questions */}
              {insights?.questions && insights.questions.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4 flex items-center space-x-2">
                    <HelpCircle className="w-5 h-5 text-blue-500" />
                    <span>Suggested Questions</span>
                  </h3>
                  <div className="space-y-2">
                    {insights.questions.map((question, index) => (
                      <button
                        key={index}
                        onClick={() => onQuestionClick(question)}
                        className="w-full p-3 text-left bg-gray-700 hover:bg-gray-600 rounded-lg text-white text-sm transition-colors"
                      >
                        {question}
                      </button>
                    ))}
                  </div>
                </div>
              )}

              {/* Knowledge Gaps */}
              {insights?.gaps && insights.gaps.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4">Content Gaps</h3>
                  <div className="space-y-2">
                    {insights.gaps.map((gap, index) => (
                      <div
                        key={index}
                        className="p-3 bg-amber-900/20 border border-amber-700/30 rounded-lg"
                      >
                        <p className="text-amber-200 text-sm">{gap}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Concept Clusters */}
              {insights?.clusters && insights.clusters.length > 0 && (
                <div>
                  <h3 className="text-lg font-semibold text-white mb-4">Concept Clusters</h3>
                  <div className="space-y-3">
                    {insights.clusters.map((cluster) => (
                      <div key={cluster.id} className="p-3 bg-gray-700 rounded-lg">
                        <h4 className="font-medium text-white mb-2">{cluster.label}</h4>
                        <div className="flex flex-wrap gap-1">
                          {cluster.concepts.map((concept, index) => (
                            <span
                              key={index}
                              className="px-2 py-1 bg-gray-600 text-gray-300 text-xs rounded"
                            >
                              {concept}
                            </span>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Metadata */}
              {insights?.metadata && (
                <div className="pt-4 border-t border-gray-700">
                  <h4 className="text-sm font-medium text-gray-400 mb-2">Knowledge Graph Info</h4>
                  <div className="text-xs text-gray-500 space-y-1">
                    {insights.metadata.entityCount && (
                      <p>Entities: {insights.metadata.entityCount}</p>
                    )}
                    {insights.metadata.source && (
                      <p>Source: {insights.metadata.source === 'google-kg' ? 'Google Knowledge Graph' : 'Fallback Analysis'}</p>
                    )}
                    {insights.metadata.timestamp && (
                      <p>Generated: {new Date(parseInt(insights.metadata.timestamp)).toLocaleString()}</p>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};